monome/druid

- README.md
- druid.py
Using pyserial's `comports` function to grab available ports & matching on crow's identification string.
Tested working on linux & mac.
Removed `readline` as it was not being used & is not available on windows. That said, I see `can't find crow device` on windows, and promptly gave up.
Added the `ser.close()` at the end to make sure the script released the port on quitting (not sure if this is necessary).
> Auto-discover serial port

- README.md
- druid.py
Ahoy! Just figured out the conditional import thing (or rather, ignore failed import of readline), and the serial port discovery now works on windows too.
> Windows support

- druid.py
"executable modules" are a common pattern in Python. This change adopts the standard style which allows a module to be executed directly if it is the main source file otherwise behave as a normal module if being imported.
In addition a shebang line was added which should allow the script to be directly executed on macOS and Linux machines.
https://wiki.python.org/moin/ExecutableModules
> idiomatic executable module style

- druid.py
Fixes #8 
The [problem](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/556) is that prompt_toolkit replaces tabs with `^I`, [here](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/1e4b44e090088310f211357869555bc0decf1b09/prompt_toolkit/layout/screen.py#L50). This replaces this with two spaces instead. It has to be two spaces because this is the same width as `^I`, otherwise the linked issue thread indicates prompt_toolkit won't calculate character widths correctly.
> patch prompt_toolkit to use spaces for tabs

- crowlib.py
**REQUIRES crow-v1.0.0+**
Uses a far simplified upload/execute sequence (see https://github.com/monome/crow/pull/193).
Increased delays between-lines when uploading a file (2ms per line), and decreased delays at end of upload as crow handles the cleanup by itself.
DO NOT MERGE until we post the official crow 1.0.0
> bulk run/flash setup & longer delays

- .gitignore
- README.md
- download.py
- requirements.txt
- setup.py
- setup.sh
- src/druid/crowlib.py
- src/druid/main.py
- upload.py
As prepwork for publishing to pypi and to make it clearer/simpler to install and use.
Also fixed a bunch of PEP8/linting issues.
I only fixed the simple/non-invasive ones though, will have a look at the rest later.
How to use after these changes (see readme for more instructions):
```bash
$ pip install --user .
Obtaining file:///home/simon/src/monome/druid
Collecting prompt-toolkit>=2.0.10 (from monome-druid==0.1)
Using cached https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl
Collecting pyserial>=3.4 (from monome-druid==0.1)
Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting wcwidth …
```
> Restructure to normal python package

- setup.py
- src/druid/repl.py
Fixed a bunch of linting issues and cleaned up the code a bit.
Pylint is now slightly happier:
```
$ pylint src/druid/repl.py
************* Module repl
src/druid/repl.py:42:0: R0912: Too many branches (13/12) (too-many-branches)
src/druid/repl.py:112:0: C0116: Missing function or method docstring (missing-function-docstring)
src/druid/repl.py:113:4: W0603: Using the global statement (global-statement)
src/druid/repl.py:116:8: W0603: Using the global statement (global-statement)
src/druid/repl.py:119:8: W0702: No exception type(s) specified (bare-except)
src/druid/repl.py:122:15: W0613: Unused argument 'buff' (unused-argument)
src/druid/repl.py:153:4: W0612: Unused variable 'result' (unused-variable)
src/druid/repl.py:160:0: C0116: Missing function or method docstring …
```
> Linting fixes pt1

- setup.py
Instead of an implicit namespace package
This way we don't depend on Python3's implicit namespace packages which needs a newer setuptools to work, reducing our installation dependencies.
Fixes #39
> Change druid to a regular package

- README-development.md
the name of the file is .venv, not ./venv
> fix typo in dev readme

- src/druid/crowlib.py
Since crow expects CRLF line endings (I am not exactly sure what it is causes problems with LF-only line endings), line endings need to be adjusted when uploading file contents. Sending line endings as-is on Linux and Mac would typically only send `\n`, causing upload failures / hangs / other odd states. This patch corrects line endings by using `rstrip` to remove trailing whitespace and then adding `\r\n` to each line sent during upload.
This explains why the patch https://github.com/monome/crow/pull/232 improves upload stability a lot on Windows, but uploads were still failing for me on Mac - on Windows the line endings are already CRLF. In combination with https://github.com/monome/crow/pull/232 I believe this patch resolves a lot of upload issues, possibly including …
> ensure crlf line endings to prevent upload crashes

- src/druid/crowlib.py
- src/druid/repl.py
Fixes the sluggishness of the interface! The issue was how we were polling the `serial.read()` where it would *always* wait for the timeout because we asked for "lots of data", and this would fail to release the asyncio thread.
Fixed by reducing the timeout to 10ms in crowlib.py (was 100ms, causing the 10fps). Feels super snappy now. Input polls are more much more snappy!
Reduced the reconnect rate so druid will auto-connect much faster in case of a pulled cable. This really relies on #49 as otherwise the console fills up fast! Tested on Linux as has no effect on CPU usage when polling for the serial port this fast. Main benefit here is it reduces the delay we have to set on crow before sending a startup message.
> decrease serial timeout & increase reconnect poll

- src/druid/repl.py
fixes #43 
fixes #14 
Track whether a connection is currently active. Only print connect/disconnect on the state change.
On boot, run the 'reconnect' routine, which is essentially just connect that doesn't quit.
NB: I made the CLI options `sys.exit(1)` if no crow is found on boot because they would otherwise just load into the REPL if no device was found which seems incorrect behaviour for a CLI tool. Instead it returns with an errorcode and tells the user there's no crow detected.
> boot without connection & only print disconnected once

- src/druid/repl.py
Before this PR, if you try and set a variable called `p`, `q` or `h`, the parser would treat it as if you were calling the special druid commands. this solves this issue so that the letter's must be the *only* text entered.
> protect against p,h and q vars

- src/druid/crowlib.py
- src/druid/repl.py
Turns out the line-ending issue was potentially a red-herring.
This PR removes the forced line-ending encoding as crow should handle either line-endings gracefully.
This does however introduce a gross hack to solve a problem where transmissions of exactly 64bytes would cause crow to stop receiving further data. This solution adds an additonal newline character which crow discards anyway, and remains active. Confusingly this hack is ony needed on windows & osx (not linux).
64bytes is the size of the USB-buffer endpoints on crow. See the following files in the crow project:
crow/submodules/STM32_Cube_F7/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h @114-115
crow/submodules/STM32_Cube_F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h @58
Tested on lin/win/osx …
> hack to handle 64byte length lines

- .git_archival.txt
- .gitattributes
- .gitignore
- setup.py
- src/druid/__init__.py
- src/druid/cli.py
This uses https://pypi.org/project/setuptools-scm/ + https://pypi.org/project/setuptools-scm-git-archive/ which is a bit "magic", but from my testing this is the only way to get the version automatically with the following criteria:
- The only action necessary to update the version is `git tag`
- Release archives from GitHub should work and show the correct version
- During development it should be clear that a "development version" is being used. Ideally the shorthash + something like `dev` should be shown
Some output examples:
```
$ druid --version          
druid, version 0.1.2.dev17+g971de94
$ git tag -a 0.1.3 -m "thisisatest"
$ druid --version
druid, version 0.1.3
$ echo "foo" > test.txt
$ git add test.txt
$ druid --version
druid, version 0.1.4.dev0+g07eb4c8.d20191021
```
And when …
> Add version info to druid package and use it for CLI version output

- src/druid/repl.py
This is just to give an indication that crow is not attached when druid boots, as suggested [here](https://github.com/monome/druid/issues/43#issuecomment-543416049). This only changes the `crowreconnect` call that's made before starting the repl.
> show <crow not found> on startup

- src/druid/repl.py
Just doesn't `run_until_complete` the background task after it has been cancelled, since I think this is all the CancelledError means. @simonvanderveldt this feels almost too easy to be the "right" way to fix #12? Works on Windows and OSX, no hanging shell, no lingering Python processes.
The `if is_connected` check is just to prevent a traceback if you quit out of druid without having connected a device, because in that case the `crow` global is `None`.
> fix shutdown exceptions (?) by not waiting for canceled task

- src/druid/cli.py
Fixes issue where after either upload or download the `^^print` request would not reliably work due to the buffer being incomplete.
This was likely introduced / exacerbated when the serial object's timeout was reduced to 0.01seconds (from 0.1s).
@csboling I think this should fix this issue: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 31: invalid continuation byte` if you could test?
> add sleep after ^^p  request to ensure data is valid & ready

- setup.py
- src/druid/__init__.py
Apparently `setuptools_scm` doesn't work for releases (sdist or wheels), not entirely sure why yet, but for now falling back to just getting the version from the installed distribution, which should be good enough for regular usage.
We still keep the dev versions when someone is working on the code this way.
> Fix version info for releases

- README.md
Upgrading setuptools should no longer be necessary in most/all situations now that #36 has been merged.
[edit] Or do we simply want to remove this from the readme as a whole and link to the docs on the monome site instead?
> readme: Upgrading setuptools should no longer be necessary

- src/druid/crowlib.py
Fixes #63 
Results in writing an extra newline if the file contains one, but this should be fine. It does appear I need to clear the user script if one has already been uploaded without a newline.
> always add EOF newline when writing file

- setup.py
Fixes #64 
prompt-toolkit 3.0.0 [released](https://pypi.org/project/prompt-toolkit/3.0.0/) a few days ago, which is API-incompatible with prompt-toolkit 2.0.0. This breaks new druid installs because it attempts to satisfy the constraint `prompt-toolkit>=2.0.10` with v3.0.0. This patch adds a constraint to require `>=2.0.10,<3.0` as a quick fix until we can update to the new version.
> constrain prompt-toolkit to < 3.0

- src/druid/cli.py
- src/druid/repl.py
Addresses #70 by adding an option to avoid using the internal repl theme colors, meaning the druid repl will inherit the user's specified terminal theme colors. Option needs to be passed to `repl` command:
```
druid repl --no-theme
```
> add option to override internal repl theme

- src/druid/crow.py
1.1.0 would not connect to my crow.
i can't explain why, but if we don't first match on the `hwid` the `for portinfo` line loops infinitely, trying to process the same device (which for me is not the correct device, hence never connecting).
the benefit to this PR is that it matches on the PID/VID as well as the known crow manufacturer-string.
this is tested on an Ubuntu VM, so testing on a mac & windows would be great too.
still, it's a hotfix as the current druid release is broken in pip (at least if you have more than 1 serial device attached).
> fix serial port detection

- src/druid/crow.py
Returning windows to 1.0 connection style where it would match VID:PID pair. maintains improved connection logic for Linux / Mac OS (mfg string) and ignores this extra test on windows (which doesn't have access to mfg string).
> Fix windows connection issue to be more picky

- src/druid/repl.py
Fixes #20, but disables the ability to scroll back up through the output with the mouse.
I personally need to select and copy error messages more than I need to scroll back up through the output.
Problem originates in `prompt-toolkit`. See https://github.com/prompt-toolkit/ptpython/issues/329 for more info.
> Disable mouse support to restore ability to select text
